#doctests and unitests:
#    script: pytest --doctest-modules -v --ignore=GUIs

# Temporarily added back old testing
unittests:
  script: python -m unittest discover tests -v
core doctests:
  script: python -m doctest -v AmpScan/core.py
registration doctests:
  script: python -m doctest -v AmpScan/registration.py
align doctests:
  script: python -m doctest -v AmpScan/align.py
