language: python
cache: pip
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest --doctest-modules -v --ignore=GUIs --ignore=docs
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d161cef641a852a535e3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
