name: py3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.11=py_3
  - anaconda-client=1.7.1=py_0
  - appdirs=1.4.3=py_1
  - cython=0.28.5
  - decorator=4.3.0=py_0
  - docutils=0.14=py35_0
  - freetype=2.9.1
  - future=0.16.0=py35_2
  - ipykernel=4.8.2=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.0=py_0
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - msgpack-python=0.5.6
  - nb_anacondacloud=1.4.0=py35_0
  - nb_conda=2.2.1=py35_0
  - nb_conda_kernels=2.1.1=py35_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - nbpresent=3.0.2=py35_1
  - nbsphinx=0.3.4=py_0
  - notebook=5.6.0=py35_0
  - numpydoc=0.8.0=py_1
  - packaging=17.1=py_0
  - pandas=0.23.4
  - pandoc=2.2.2
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pickleshare=0.7.4=py35_0
  - pip=18.0=py35_1
  - pycparser=2.18=py_1
  - pygments=2.2.0=py_1
  - python=3.5.5
  - pyqt
  - setuptools=40.0.0=py35_1
  - sphinx=1.7.5=py35_0
  - sphinx_rtd_theme=0.4.1=py_0
  - widgetsnbextension=3.4.0=py35_0
  - _nb_ext_conf=0.4.0=py35_1
  - freetype
  - matplotlib=2.2.2
  - numpy=1.15.0
  - numpy-base=1.15.0
  - scipy=1.1.0
  - sphinxcontrib=1.0
  - vtk
  - pythreejs
  - pip:
    - git+https://git.soton.ac.uk/js22g12/AmpScan
    - msgpack==0.5.6
    - pi==0.1.2
    - pockets==0.6.2
    - sphinxcontrib-napoleon==0.6.1
